### ISSUE TITLE
Re-implement troop transport at the ranges

### ISSUE THREAD

**Issue by theendsofinvention** [132nd-vWing/132nd-Virtual-Wing-Training-Mission-Tblisi#15]
Troop transport should be available at all ranges.

Players should be able to spawn trucks containing infantry.

Each truck could then be used to transport & unload the infantry anywhere around the range.

**Comment by 132nd-Entropy** [comment]
Im confused, isnt that the case already? All ranges have a truck loaded with infantry that can be transported, loaded and unloaded anywhere on the map?

**Comment by theendsofinvention** [comment]
All range currently have one truck, which is able to unload troops anywhere, but not load them again, except in the spawning area.

I would like to make an on-demand version of this, with a dedicated sub-menu.

There would me a maximum amount of trucks per range (let's say 6 for the sake of the example).

Players could spawn from 0 to 6 trucks, and each truck would receive an infantry group.

A sub-menu would be created for those trucks, allowing players to unload and load infantry in the truck (unload only if the truck has infantry and load only if the truck is close enough to the infantry).

An implementation with CTLD would be ideal and should be possible.

**Comment by 132nd-Entropy** [comment]
initially we had 2 trucks, but we cut it down to 1 since it became confusing for the user. More than one can anytime be added if you find a need for it. 
also, they are fully CTLD capable, meaning, the JTAC player can hop into the truck and re-load the troops again and drive them anywhere. The F10 menu option to unload them was more for FAC(A)s who cant leave their aircraft. 

So the system as it is now it functional I'd say. If you find a way to improve it of course you are more than welcome!! :D

**Comment by theendsofinvention** [comment]
Oh roger !
I thought the F10 system was the way to got, but now I understand it's only a crutch. Thank you !
