### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by theendsofinvention** [132nd-vWing/132nd-Virtual-Wing-Training-Mission-Tblisi#22]
With the ever-increasing amount of functionalities present in the TRMT, I feel that it would be useful for the pilots if we wrote a short documentation about it.

Namely, the effects of the different radio commands, and all the little "peculiarities" of the mission (IF this, THEN that).

**Comment by theendsofinvention** [comment]
Request from Neck: merge all document relevant to the TRMT (OI ranges, SPINS, ...) into one master document.

@132ndNeck Is there already someone assigned to this task ?

**Comment by 132nd-Entropy** [comment]
I think this is a great idea, maybe we could even make a post and ask if someone other than us is interested in compiling such a document? 

on a side note, I think having the most crucial infos such as tanker freqs and tacans etc in the in game mission brief really is beneficial, I volunteer to keep this briefing up to date

**Comment by 132ndNeck** [comment]
That would be great, however, I doubt anyone is really eager to do it, so I will start once I have setup everything for tonight, and the mission for next sunday is ready.

With regard to keeping things in the mission brief, I would suggest to avoid having the same information several places (hence why I want to collect everything one place). This way it will be easier to maintain, and when we change something (which will happen at some points) we only need to change the information one place, and we then avoid getting conflicting information because someone (like me) forgot to update it at all places. 

But that is just my suggestion, and I am open for keeping it in the brief aswell.

**Comment by 132nd-Entropy** [comment]
rgr, makes sense!
right now, the tanker info is in the brief  and updated, and since this is unlikely to change often maybe its a good idea to leave it in, for externals who forgot to look up the tanker freq, but it can as well be deleted I dont mind either way. I personally find it very convenient to look up the tacan and freq for the tanker, using the brief, but I can as well mkae a kneeboard file from the new centralized document so Im fine with either solution :)

**Comment by theendsofinvention** [comment]
Actually, we could have the documentation here, in Markdown format for example.

That would tie the documentation and the state of the mission, and that would also allow for versioning & collaborative edits of the doc.

**Comment by 132ndNeck** [comment]
I suggest we put everything in the Mission brief in the Mission Database. Then we can have all relevant information in one place that is specific to that mission. Right now the mission brief for the training mission is outdated, and have not been updated for quite some time!

If there is specific information that is only valid for that one single event, it can be put in the event information.

**Comment by 132nd-Entropy** [comment]
are we talking about the same thing? I was talking about the briefing screen that you edit in the mission editor and can access in game while flying? The DCS in-game mission briefing? Because that is not outdated at all and I updated it as soon as we put in the new tankers. Why you say it is outdated and has not been updated for quite some time?
 
Again, I find it very useful for looking up tacan and freqs for the 5 tankers we have in the air, and if you fly in VR you cant easily alt tab to your notes  or other documents. Especially for externals that is useful to have. 
If you for some reason really want to take out the mission briefing from the trmt then by all means do it of course, but I can simply not see the harm to leave it in as long as its updated, which it is. :)

**Comment by theendsofinvention** [comment]
IMO there are three different aspect in this discussion already:

* The documentation in the form of Microsoft Word files, outside of the TRMT, that currently comprises many different files and should be merged
* The documentation within the TRMT, that is kept up to date with the mission (thx @132nd-Entropy )
* The documentation of the functionalities that we keep adding into the mission (ex: explain to the pilot the SAR radio menus)

The latest was my primary concern, I think I should write a little stub of documentation to help the newcomers navigate their way into our system.

**Comment by 132ndNeck** [comment]
No I was talking about the briefing in on the 132nd website. The full briefing for the Training Mission.

No, I do not see any reason for deleting it from the mission brief in DCS in-game mission briefing. 
I just see the benefit of only having information one place, so you dont need to do double work when changing something. I don't think it will happen often, so it is likely not an issue.

**Comment by 132nd-Entropy** [comment]
copy, agreed
